Julian Example Endpoint
t1waz/school_backend pull request #3
Opened 2022-09-30 14:39 UTC by JulianKorgol

2022-10-01 19:20 UTC, t1waz requested changes
pls refactor

2022-10-01 19:20 UTC, t1waz commented on backend/main.py
> +from datetime import datetime
imports should be sorted

2022-10-01 19:20 UTC, t1waz commented on backend/main.py
> +    date = str(datetime.now())
variable date is used only in one place so it can be directly used in dict

2022-10-01 19:21 UTC, t1waz commented
pls tell rest of students that there is deadline with PR until next meet :)

2022-10-02 09:48 UTC, t1waz commented
pls send this discord to other students (we will try to use it for communication) https://discord.gg/fpuqSQBk

2022-10-02 12:28 UTC, JulianKorgol commented
I posted and sent the link. :D

2022-10-02 20:06 UTC, t1waz approved these changes
LGMT

2022-10-02 20:06 UTC, merged