adamCzyzBranchIdea
t1waz/school_backend pull request #4
Opened 2022-10-01 16:43 UTC by niebieskiczlowiek

Created an endpoint under /superFunEndpoint with a message coded in base64

2022-10-01 19:19 UTC, t1waz requested changes
pls refactor CamelCase to snake_case

2022-10-01 19:19 UTC, t1waz commented on backend/main.py
> +async def superFunEndpoint(request):
method names in python are always snake_case not CamelCase.

pls refactor

2022-10-01 19:19 UTC, t1waz commented on backend/main.py
> +    Route('/superFunEndpoint', superFunEndpoint),
consider changing name to capybara

2022-10-01 19:22 UTC, t1waz commented
pls tell rest of students that there is deadline with PR until next meet :)

2022-10-02 09:38 UTC, niebieskiczlowiek commented
refactored method name to capybara_endpoint and the endpoint name to just capybara (and reminded students of deadline :) )

2022-10-02 09:42 UTC, t1waz approved these changes
LGTM

2022-10-02 09:42 UTC, t1waz commented
LGTM, pls rebase

2022-10-02 09:49 UTC, t1waz commented
pls send this discord to other students (we will try to use it for communication) https://discord.gg/fpuqSQBk

2022-10-05 07:40 UTC, merged